graph TD
    Eden["<b>Eden</b><br>Genesis 2:8"] --> Garden["<b>Garden</b><br>In the east<br>the tree of life<br>the tree of the knowledge of good and evil<br>Adam, Eve, the serpent<br>Genesis 2:8-9, 2:15, 2:22, 3:1, 3:20"]
    Eden --> Pishon["<b>Pishon River</b><br>Genesis 2:11"]
    Eden --> Gihon["<b>Gihon River</b><br>Genesis 2:13"]
    Eden --> Tigris["<b>Tigris River</b><br>Genesis 2:14"]
    Eden --> Euphrates["<b>Euphrates River</b><br>Genesis 2:14"]
    Pishon --> Havilah["<b>Havilah</b><br>Gold, bdellium, onyx stone<br>Genesis 2:11-12"]
    Gihon --> Cush["<b>Cush</b><br>Genesis 2:13"]
    Tigris --> Assyria["<b>Assyria</b><br>Genesis 2:14"]
    Eden --> Cherubim["<b>Cherubim</b><br>Genesis 3:24"]
    Eden --> FlamingSword["<b>A Flaming sword</b><br>Genesis 3:24"]
    Eden --> Nod["<b>Nod</b><br>East of Eden<br>Cain and his wife<br>Genesis 4:16"]
    Nod --> Enoch["<b>Enoch</b><br>Genesis 4:17"]
    Ararat["<b>Mountains of Ararat</b><br>Genesis 8:4"]
    