graph TD
    God["<b>God</b><br> Genesis 1:1"] --> Adam["<b>1.1 Adam</b><br>Put to the garden of Eden.<br>Then sent out of the garden.<br>Genesis 2:7, 2:20"]
    God --> Eve["<b>1.2 Eve</b><br>Born in the garden of Eden.<br>Genesis 2:22, 3:20"]
    Adam --> Cain["<b>2.1 Cain</b><br>Eden, Nod<br>A worker of the ground<br>Genesis 4:1"]
    Eve --> Cain
    Adam --> Abel["<b>2.2 Abel</b><br>Eden<br>A keeper of sheep<br>Killed by Cain<br>Genesis 4:2, 4:8"]
    Eve --> Abel
    Cain --> Enoch["<b>3. Enoch</b><br>Genesis 4:17"]
    CainWife["<b>Cain's Wife</b><br>Genesis 4:17"] --> Enoch
    Enoch --> Irad["<b>4. Irad</b><br>Genesis 4:18"]
    Irad --> Mehujael["<b>5. Mehujael</b><br>Genesis 4:18"]
    Mehujael --> Methushael["<b>6. Methushael</b><br>Genesis 4:18"]
    Methushael --> Lamech["<b>7. Lamech</b><br>Genesis 4:18"]
    Lamech --> Jabal["<b>8.1 Jabal</b><br>The father of those who dwell in tents and have livestock<br>Genesis 4:20"]
    Adah["<b>Adah</b><br>Genesis 4:19"] --> Jabal
    Lamech --> Jubal["<b>8.2 Jubal</b><br>The father of all those who play the lyre and pipe<br>Genesis 4:21"]
    Adah --> Jubal
    Lamech --> TubalCain["<b>8.3 Tubal-Cain</b><br>The forger of all instruments of bronze and iron<br>Genesis 4:22"]
    Zillah["<b>Zillah</b><br>Genesis 4:19"] --> TubalCain
    Lamech --> Naamah["<b>8.4 Naamah</b><br>Genesis 4:22"]
    Zillah --> Naamah
    Adam --> Seth["<b>2.3 Seth</b><br>Genesis 4:25"]
    Eve --> Seth
    Seth --> Enosh["<b>3. Enosh</b><br>Genesis 4:26"]
    Enosh --> Kenan["<b>4. Kenan</b><br>Genesis 5:9"]
    Kenan --> Mahalalel["<b>5. Mahalalel</b><br>Genesis 5:12"]
    Mahalalel --> Jared["<b>6. Jared</b><br>Genesis 5:15"]
    Jared --> Enoch2["<b>7. Enoch</b><br>Walked with God<br>Genesis 5:18"]
    Enoch2 --> Methuselah["<b>8. Methuselah</b><br>Genesis 5:21"]
    Methuselah --> Lamech2["<b>9. Lamech</b><br>Genesis 5:25"]
    Lamech2 --> Noah["<b>10. Noah</b><br>On the mountains of Ararat after the flood<br>Walked with God<br>Genesis 5:29, 6:9"]
    Noah --> Shem["<b>11.1 Shem</b><br>Genesis 5:32"]
    Noah --> Ham["<b>11.2 Ham</b><br>Genesis 5:32"]
    Noah --> Japheth["<b>11.3 Japheth</b><br>Coastland peoples are from his sons<br>Genesis 5:32, 10:5"]
    God --> SonsOfGod["<b>Sons of God</b><br>Genesis 6:2"]
    SonsOfGod --> Nephilim["<b>Nephilim</b><br>Genesis 6:4"]
    DaughtersOfMan["<b>Daughters of man</b><br>Genesis 6:2"] --> Nephilim
    Ham --> Canaan["<b>12.1. Canaan</b><br>Sidon, Gerar, Gaza, Sodom, Gomorrah, Admah, Zeboiim, Lasha<br>Genesis 9:18, 10:19"]
    Japheth --> Gomer["<b>12.1 Gomer</b><br>Genesis 10:2"]
    Japheth --> Magog["<b>12.2 Magog</b><br>Genesis 10:2"]
    Japheth --> Madai["<b>12.3 Madai</b><br>Genesis 10:2"]
    Japheth --> Javan["<b>12.4 Javan</b><br>Genesis 10:2"]
    Japheth --> Tubal["<b>12.5 Tubal</b><br>Genesis 10:2"]
    Japheth --> Meshech["<b>12.6 Meshech</b><br>Genesis 10:2"]
    Japheth --> Tiras["<b>12.7 Tiras</b><br>Genesis 10:2"]
    Gomer --> Ashkenaz["<b>13.1 Ashkenaz</b><br>Genesis 10:3"]
    Gomer --> Riphath["<b>13.2 Riphath</b><br>Genesis 10:3"]
    Gomer --> Togarmah["<b>13.3 Togarmah</b><br>Genesis 10:3"]
    Javan --> Elishah["<b>13.1 Elishah</b><br>Genesis 10:4"]
    Javan --> Tarshish["<b>13.2 Tarshish</b><br>Genesis 10:4"]
    Javan --> Kittim["<b>13.3 Kittim</b><br>Genesis 10:4"]
    Javan --> Dodanim["<b>13.4 Dodanim</b><br>Genesis 10:4"]
    Ham --> Cush["<b>12.2 Cush</b><br>Genesis 10:6"]
    Ham --> Egypt["<b>12.3 Egypt</b><br>Genesis 10:6"]
    Ham --> Put["<b>12.4 Put</b><br>Genesis 10:6"]
    Cush --> Seba["<b>13.1 Seba</b><br>Genesis 10:7"]
    Cush --> Havilah["<b>13.2 Havilah</b><br>Genesis 10:7"]
    Cush --> Sabtah["<b>13.3 Sabtah</b><br>Genesis 10:7"]
    Cush --> Raamah["<b>13.4 Raamah</b><br>Genesis 10:7"]
    Cush --> Sabteca["<b>13.5 Sabteca</b><br>Genesis 10:7"]
    Cush --> Nimrod["<b>13.6 Nimrod</b><br>First mighty man on earth.<br>A mighty hunter before the Lord.<br>His kindom: Babel, Erech, Accad, Calneh, in the land of Shinar<br>Assyria, Nineveh, Rehoboth-Ir, Calah, Resen, which is the great city<br>Genesis 10:8-12"]
    Egypt --> Ludim["<b>13.1 Ludim</b><br>Genesis 10:13"]
    Egypt --> Anamim["<b>13.2 Anamim</b><br>Genesis 10:13"]
    Egypt --> Lehabim["<b>13.3 Lehabim</b><br>Genesis 10:13"]
    Egypt --> Naphtuhim["<b>13.4 Naphtuhim</b><br>Genesis 10:13"]
    Egypt --> Pathrusim["<b>13.5 Pathrusim</b><br>Genesis 10:14"]
    Egypt --> Casluhim["<b>13.6 Casluhim</b><br>From whom the Philistines came<br>Genesis 10:14"]
    Egypt --> Caphtorim["<b>13.7 Caphtorim</b><br>Genesis 10:14"]
    Canaan --> Sidon["<b>13.1 Sidon</b><br>Genesis 10:15"]
    Canaan --> Heth["<b>13.2 Heth</b><br>Genesis 10:15"]
    Canaan --> Jebusites["<b>13.3 Jebusites</b><br>Genesis 10:16"]
    Canaan --> Amorites["<b>13.4 Amorites</b><br>Genesis 10:16"]
    Canaan --> Girgashites["<b>13.5 Girgashites</b><br>Genesis 10:16"]
    Canaan --> Hivites["<b>13.6 Hivites</b><br>Genesis 10:17"]
    Canaan --> Arkites["<b>13.7 Arkites</b><br>Genesis 10:17"]
    Canaan --> Sinites["<b>13.8 Sinites</b><br>Genesis 10:17"]
    Canaan --> Arvadites["<b>13.9 Arvadites</b><br>Genesis 10:18"]
    Canaan --> Zemarites["<b>13.10 Zemarites</b><br>Genesis 10:18"]
    Canaan --> Hamathites["<b>13.11 Hamathites</b><br>Genesis 10:18"]
    Shem --> Elam["<b>12.1 Elam</b><br>Genesis 10:22"]
    Shem --> Asshur["<b>12.2 Asshur</b><br>Genesis 10:22"]
    Shem --> Arpachshad["<b>12.3 Arpachshad</b><br>Genesis 10:22"]
    Shem --> Lud["<b>12.4 Lud</b><br>Genesis 10:22"]
    Shem --> Aram["<b>12.5 Aram</b><br>Genesis 10:22"]
    Aram --> Uz["<b>13.1 Uz</b><br>Genesis 10:23"]
    Aram --> Hul["<b>13.2 Hul</b><br>Genesis 10:23"]
    Aram --> Gether["<b>13.3 Gether</b><br>Genesis 10:23"]
    Aram --> Mash["<b>13.4 Mash</b><br>Genesis 10:23"]
    Arpachshad --> Shelah["<b>13.1 Shelah</b><br>Genesis 10:24"]
    Shelah --> Eber["<b>14.1 Eber</b><br>Genesis 10:24"]
    Eber --> Peleg["<b>15.1 Peleg</b><br>In his days the earth was divided.<br>Genesis 10:25"]
    Eber --> Joktan["<b>15.2 Joktan</b><From Mesha in the direction of Sephar.><br>Genesis 10:25, 10:30"]
    Joktan --> Almodad["<b>16.1 Almodad</b><br>Genesis 10:26"]
    Joktan --> Sheleph["<b>16.2 Sheleph</b><br>Genesis 10:26"]
    Joktan --> Hazarmaveth["<b>16.3 Hazarmaveth</b><br>Genesis 10:26"]
    Joktan --> Jerah["<b>16.4 Jerah</b><br>Genesis 10:26"]
    Joktan --> Hadoram["<b>16.5 Hadoram</b><br>Genesis 10:27"]
    Joktan --> Uzal["<b>16.6 Uzal</b><br>Genesis 10:27"]
    Joktan --> Diklah["<b>16.7 Diklah</b><br>Genesis 10:27"]
    Joktan --> Obal["<b>16.8 Obal</b><br>Genesis 10:28"]
    Joktan --> Abimael["<b>16.9 Abimael</b><br>Genesis 10:28"]
    Joktan --> Sheba["<b>16.10 Sheba</b><br>Genesis 10:28"]
    Joktan --> Ophir["<b>16.11 Ophir</b><br>Genesis 10:29"]
    Joktan --> Havilah2["<b>16.12 Havilah</b><br>Genesis 10:29"]
    Joktan --> Jobab["<b>16.13 Jobab</b><br>Genesis 10:29"]
    
    

    









    

    