graph TD
    Eden["<b>Eden</b><br>Genesis 2:8"] --> Garden["<b>Garden</b><br>In the east<br>the tree of life<br>the tree of the knowledge of good and evil<br>Adam, Eve, the serpent<br>Genesis 2:8-9, 2:15, 2:22, 3:1, 3:20"]
    Eden --> Pishon["<b>Pishon River</b><br>Genesis 2:11"]
    Eden --> Gihon["<b>Gihon River</b><br>Genesis 2:13"]
    Eden --> Tigris["<b>Tigris River</b><br>Genesis 2:14"]
    Eden --> Euphrates["<b>Euphrates River</b><br>Genesis 2:14"]
    Pishon --> Havilah["<b>Havilah</b><br>Gold, bdellium, onyx stone<br>Genesis 2:11-12"]
    Gihon --> Cush["<b>Cush</b><br>Genesis 2:13"]
    Tigris --> Assyria["<b>Assyria</b><br>Genesis 2:14"]
    Eden --> Cherubim["<b>Cherubim</b><br>Genesis 3:24"]
    Eden --> FlamingSword["<b>A Flaming sword</b><br>Genesis 3:24"]
    Eden --> Nod["<b>Nod</b><br>East of Eden<br>Cain and his wife<br>Genesis 4:16"]
    Nod --> Enoch["<b>Enoch</b><br>Genesis 4:17"]
    Ararat["<b>Mountains of Ararat</b><br>After the flood.<br>Genesis 8:4"]
    Ararat --> Shinar["<b>Shinar</b><br>Genesis 10:10"]
    Shinar --> Babel["<b>Babel</b><br>In the land of Shinar<br>Genesis 10:10"]
    Shinar --> Erech["<b>Erech</b><br>In the land of Shinar<br>Genesis 10:10"]
    Shinar --> Accad["<b>Accad</b><br>In the land of Shinar<br>Genesis 10:10"]
    Shinar --> Calneh["<b>Calneh</b><br>In the land of Shinar<br>Genesis 10:10"]
    Shinar --> Assyria["<b>Assyria</b><br>Genesis 10:11"]
    Assyria --> Nineveh["<b>Nineveh</b><br>Genesis 10:11"]
    Assyria --> RehobothIr["<b>Rehoboth-Ir</b><br>Genesis 10:11"]
    Assyria --> Calah["<b>Calah</b><br>Genesis 10:11"]
    Assyria --> Resen["<b>Resen</b><br>The great city<br>Genesis 10:12"]
    Ararat --> Sidon["<b>Sidon</b><br>Genesis 10:19"]
    Ararat --> Gerar["<b>Gerar</b><br>Genesis 10:19"]
    Ararat --> Gaza["<b>Gerar</b><br>Genesis 10:19"]
    Ararat --> Sodom["<b>Sodom</b><br>Genesis 10:19"]
    Ararat --> Gomorrah["<b>Gomorrah</b><br>Genesis 10:19"] 
    Ararat --> Admah["<b>Admah</b><br>Genesis 10:19"]
    Ararat --> Zeboiim["<b>Zeboiim</b><br>Genesis 10:19"]
    Ararat --> Lasha["<b>Lasha</b><br>Genesis 10:19"]
    Ararat --> Mesha["<b>Mesha</b><br>Genesis 10:30"]
    Ararat --> Sephar["<b>Sephar</b><br>Genesis 10:30"]
    Chaldeans["<b>Chaldeans</b><br>Genesis 11:28"] --> Ur["<b>Ur</b><br>Genesis 11:28"]
    Ur --> Haran["<b>Haran</b><br>Genesis 11:31"]
    


    